name : UMC study dev CI/CD

on :
  pull_request :
    types : [closed]
  workflow_dispatch : # (2) . 수동 실행도 가능하도록

jobs :
  build :
    runs-on : ubuntu-latest
    if : github.event.pull_request.mergerd == true && github.event.pull_request.base.ref == 'develop'